(() => {'use strict';
const D=ALFORD_EXPLORE,W=ALFORD_WALK,records=W.records,people=Object.fromEntries(D.people.map(p=>[p.id,p])),places=Object.fromEntries(D.places.map(p=>[p.id,p])),features=Object.fromEntries(D.features.map(p=>[p.id,p])),scenes=Object.fromEntries(W.allScenes.map(s=>[s.id,s]));
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),paras=a=>a.map(p=>`<p>${esc(p)}</p>`).join(''),first=s=>s.match(/^.*?[.!?](?:\s|$)/)?.[0]||s;
const main=$('explore-main'),dialog=$('source-dialog');let screen='',modalOrigin=null,tree=null;
let recordFilters={person:'all',type:'all',order:'oldest'};
const viewer=new ArchiveImageViewer({viewport:$('record-scroller'),image:$('source-image'),plus:$('zoom-in'),minus:$('zoom-out'),fit:$('zoom-fit'),range:$('zoom-range'),value:$('zoom-value')});
history.scrollRestoration='manual';
try{const saved=JSON.parse(sessionStorage.getItem('alford-explore-return'));if(saved?.story){$('return-to-story').href='index.html?resume=1#'+saved.story.id;$('return-to-story').textContent='← Return to your place in the story';}}catch{}
const personCards=items=>`<div class="directory">${items.map(p=>`<a class="person-card" href="#person/${p.id}"><span class="card-meta">${esc(p.relationship)}</span><h3>${esc(p.name)}</h3><span class="card-meta">${esc(p.dates)}</span><p style="margin-top:12px">${esc(first(p.summary))}</p><span class="card-arrow">Life, family & records ↗</span></a>`).join('')}</div>`;
const featureCards=items=>`<div class="directory">${items.map(p=>`<a class="feature-card" href="#feature/${p.id}">${records[p.imageRecord]?.image?`<img loading="lazy" src="${esc(records[p.imageRecord].display||records[p.imageRecord].image)}" alt="">`:''}<h3>${esc(p.title)}</h3><p>${esc(p.dek)}</p><span class="card-arrow">Read this short history ↗</span></a>`).join('')}</div>`;
const placeCards=items=>`<div class="directory">${items.map(p=>`<a class="place-card" href="#place/${p.id}"><h3>${esc(p.name)}</h3><p>${esc(p.role)}</p><span class="card-arrow">Related people & records ↗</span></a>`).join('')}</div>`;
const chronologicalRecords=(keys,order='oldest')=>[...keys].sort((a,b)=>{
 const ay=records[a].catalogYear,by=records[b].catalogYear;
 if(ay==null&&by!=null)return 1;if(by==null&&ay!=null)return -1;
 return ((ay??0)-(by??0))*(order==='newest'?-1:1)||records[a].title.localeCompare(records[b].title);
});
const recordList=keys=>`<div class="record-list">${keys.map(k=>{const r=records[k];return `<a class="record-entry" href="#record/${k}" id="record-link-${k}"><small><span class="record-date">${esc(r.catalogDate||'Undated')}</span> · ${r.image?'SOURCE IMAGE'+(r.transcript?' & TRANSCRIPT':''):'SOURCE NOTE'}</small><strong>${esc(r.title)}</strong><span>${esc(r.caption||r.title)}</span></a>`;}).join('')}</div>`;
function matchingRecords(){return chronologicalRecords(Object.keys(records).filter(k=>
 (recordFilters.person==='all'||people[recordFilters.person]?.records.includes(k))&&
 (recordFilters.type==='all'||!!records[k].image===(recordFilters.type==='image'))),recordFilters.order);}
function updateRecords(){
 const keys=matchingRecords();$('record-results').innerHTML=keys.length?recordList(keys):'<p class="catalog-empty">No records match these filters. Choose another person or show all record types.</p>';
 $('record-count').textContent=`${keys.length} of ${Object.keys(records).length} records`;
 document.querySelectorAll('[data-record-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.recordFilter===recordFilters.type));
}
function recordBrowser(){const keys=matchingRecords();return heading('THE COLLECTION','Records & source notes','Browse in time order, or choose a person to see their records.')+`
 <div class="record-browse-controls"><label>Person<select id="record-person"><option value="all">Everyone</option>${D.people.map(p=>`<option value="${p.id}"${recordFilters.person===p.id?' selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Order<select id="record-order"><option value="oldest"${recordFilters.order==='oldest'?' selected':''}>Earliest first</option><option value="newest"${recordFilters.order==='newest'?' selected':''}>Latest first</option></select></label><button type="button" id="reset-records">Reset filters</button></div>
 <div class="filter-bar" aria-label="Record types">${[['all','All records'],['image','Images & documents'],['note','Source notes']].map(([key,label])=>`<button data-record-filter="${key}" aria-pressed="${recordFilters.type===key}">${label}</button>`).join('')}</div>
 <div class="record-browse-summary"><p class="small">Ordered by the years covered; undated material appears last.</p><p class="small" id="record-count" role="status">${keys.length} of ${Object.keys(records).length} records</p></div><div id="record-results">${recordList(keys)}</div>`;}

const links=(keys,type)=>`<div class="link-list">${keys.map(k=>`<a href="#${type}/${k}">${esc((type==='person'?people:type==='place'?places:features)[k]?.name||(type==='feature'?features[k]?.title:k))} ↗</a>`).join('')}</div>`;
const storyLinks=keys=>`<div class="life-events">${keys.map(k=>`<a href="index.html#${k}"><time>${esc(scenes[k].year)}</time><span>${esc(scenes[k].title)} ↗</span></a>`).join('')}</div>`;
const heading=(eyebrow,title,lede='')=>`<p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1>${lede?`<p class="lede">${esc(lede)}</p>`:''}`;
const breadcrumb=(route,title)=>`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="#${route}">${title}</a><span aria-hidden="true">/</span></nav>`;
function directory(group='all'){const labels={all:'Christine’s family',everyone:'All 30 people',earlier:'Earlier roots',relatives:'Close relatives',neighbours:'Neighbours',branches:'Other Alford branches'};return heading('THE FAMILY EXPLORER','Meet the Alfords','Follow Christine’s line, meet their relatives and neighbours, or look more closely at an earlier branch.')+`<div class="filter-bar" aria-label="People groups">${Object.entries(labels).map(([id,title])=>`<button data-group="${id}" aria-pressed="${id===group}">${title}</button>`).join('')}</div>`+(group==='earlier'?'<p class="catalog-note">Several records name a Jacob Alford. We keep their identities separate here so you can see what each record establishes. The story follows their proposed connection as a likely account.</p>':group==='branches'?'<p class="catalog-note">These researched people have a place in the wider Alford archive. Their presence here does not establish a connection to Christine.</p>':'')+`<p class="small" role="status">${D.people.filter(p=>group==='everyone'||(group==='all'?['john','margaret','seaborn','laura','esco','mary-lou','christine','charles'].includes(p.id):p.group===group)).length} of ${D.people.length} people · ${labels[group]||'Family'}</p>`+personCards(D.people.filter(p=>group==='everyone'||(group==='all'?['john','margaret','seaborn','laura','esco','mary-lou','christine','charles'].includes(p.id):p.group===group)));}
function profile(p){const edges=D.edges.filter(e=>e.from===p.id||e.to===p.id),related=D.features.filter(f=>f.people.includes(p.id));return breadcrumb('people','People')+heading(p.relationship,p.name,p.dates)+`<div class="related-actions"><a class="action-link primary" href="#tree/${p.id}">Find ${esc(p.name.split(' ')[0])} in the tree</a>${p.passages.length?`<a class="action-link" href="index.html#${p.passages[0]}">Read this part of the story ↗</a>`:''}</div><div class="profile-layout"><div>${paras(p.body)}${edges.length?'<h2>Family & connections</h2>'+edges.map(e=>{const id=e.from===p.id?e.to:e.from;const role=e.kind==='parent'?(e.from===p.id?'Child':'Parent'):e.kind==='spouse'?'Spouse':'Association';return `<div class="connection"><span class="small">${e.certainty==='likely'?'Likely '+role.toLowerCase():role}</span><br><a href="#person/${id}">${esc(people[id].name)}</a><p>${esc(e.qualification)}</p>${e.records.map(k=>`<a class="small" href="#record/${k}">${esc(records[k].title)} ↗</a>`).join(' · ')}</div>`;}).join(''):''}<h2>Records about ${esc(p.name.split(' ')[0])}</h2>${recordList(p.records)}</div><aside class="profile-aside">${p.passages.length?'<section><h2>In the story</h2>'+storyLinks(p.passages)+'</section>':''}${p.events.length?'<section><h2>Other recorded events</h2><div class="life-events">'+p.events.map(e=>`<div><time>${esc(e.year)}</time><span>${esc(e.label)}</span></div>`).join('')+'</div></section>':''}${p.places.length?'<section><h2>Related places</h2>'+links(p.places,'place')+'</section>':''}${related.length?'<section><h2>Read more</h2>'+links(related.map(f=>f.id),'feature')+'</section>':''}<p class="small">Archive references: ${esc(p.refs)}</p></aside></div>`;}
function feature(p){const r=records[p.imageRecord];return breadcrumb('features','Short histories')+heading('A CLOSER LOOK',p.title,p.dek)+`<div class="profile-layout"><div>${paras(p.body)}${r?.image?`<figure class="exhibit"><button type="button" data-record="${p.imageRecord}"><img src="${esc(r.display||r.image)}" alt="${esc(r.title)}"><span>${r.transcript?'Examine the image & read the transcript':'Examine this image'} ↗</span></button><figcaption>${esc(r.caption||r.citation)}</figcaption></figure>`:''}<h2>Records & sources</h2>${recordList(p.records)}</div><aside class="profile-aside"><section><h2>People</h2>${links(p.people,'person')}</section><section><h2>Related places</h2>${links(p.places,'place')}</section><section><h2>In the story</h2>${storyLinks(p.passages)}</section></aside></div>`;}
function landMap(){const M=ALfordLandscape,tracts=M.features.filter(f=>f.kind==='tract');return `<p class="small">Compare the dated tracts with the switches below the map.</p><section class="land-explorer" aria-label="Family land near the Bogue Chitto"><svg viewBox="-1700 -700 7100 7900" role="img" aria-labelledby="land-title land-desc"><title id="land-title">Three generations near the Bogue Chitto</title><desc id="land-desc">Jacob’s claim lies north of John’s later lots. Seaborn’s homestead lies south of John’s land. Toggle dated tracts to compare them.</desc>${M.features.filter(f=>f.kind==='grid').map(f=>`<path class="grid" d="${f.d}"/>`).join('')}<path class="river" d="${M.river}"/>${tracts.filter(f=>/T-JA-54|T-JSA-|T-SLA-/.test(f.id)).map(f=>`<path class="land-tract" data-layer="${f.id==='T-JA-54'?'jacob':f.id.includes('SLA')?'seaborn':f.id.includes('1861')?'john61':'john'}" d="${f.d}"/>`).join('')}<text data-layer="jacob" x="450" y="800">Jacob’s claim</text><text data-layer="jacob" class="map-small" x="450" y="1050">Settled 1807 · surveyed 1831</text><text data-layer="john" x="-1300" y="3650">John’s lots</text><text data-layer="john" class="map-small" x="-1300" y="3900">1858</text><text data-layer="seaborn" x="100" y="5800">Seaborn’s homestead</text><text data-layer="seaborn" class="map-small" x="100" y="6050">1881</text><text class="river-label" x="2850" y="2500" transform="rotate(65 2850 2500)">Bogue Chitto River</text><path d="M-1100 6400h1000m-1000 -65v130m1000 -130v130" stroke="#456248" stroke-width="14"/><text class="map-small" x="-1100" y="6770">1 kilometre</text><text class="map-small" x="4300" y="400">N ↑</text></svg><div class="land-controls"><h2 style="margin:0 0 16px">One neighbourhood, different farms</h2><p>Show the tracts together, or remove a layer to follow one generation.</p>${[['jacob','Jacob’s settlement claim · 1807 / 1831'],['john','John’s land patents · 1858'],['john61','John’s later patent · 1861'],['seaborn','Seaborn’s homestead · 1881']].map(([key,title])=>`<label><input type="checkbox" data-land="${key}" checked><span>${title}</span></label>`).join('')}<p>Reconstructed historical tract boundaries on a modern river line. These dates document claims and patents, not uninterrupted ownership.</p><a class="small" href="#record/landscape">How the map was made ↗</a><br><a class="small" href="#feature/john-field-cemeteries">John’s field and the cemeteries ↗</a></div></section>`;}
function place(p){return breadcrumb('places','Places')+heading(p.role,p.name)+(['bogue-chitto','family-cemetery'].includes(p.id)?landMap():'')+`<div class="profile-layout"><div>${paras(p.body)}<h2>Records for this place</h2>${recordList(p.records)}</div><aside class="profile-aside"><section><h2>Related people</h2>${links(p.people,'person')}</section><section><h2>In the story</h2>${storyLinks(p.passages)}</section></aside></div>`;}
function chapter(id){const c=W.chapters.find(c=>c.id===id);if(!c)return notFound();const groups=W.structure.groups.filter(g=>g.chapter===id),ids=groups.flatMap(g=>g.segments.map(s=>typeof s==='string'?s:s.id));const ps=D.people.filter(p=>p.passages.some(id=>ids.includes(id)));const fs=D.features.filter(p=>p.passages.some(id=>ids.includes(id)));const rs=[...new Set(ids.flatMap(id=>scenes[id].records))];return breadcrumb('people','Explore')+heading(c.years,c.title,c.question)+`<a class="action-link primary" href="index.html#${c.start}">Read this chapter ↗</a><h2>People in this chapter</h2>${personCards(ps)}<h2>Look more closely</h2>${featureCards(fs)}<h2>Chapter records</h2>${recordList(rs)}`;}
function search(q=''){return heading('FIND SOMETHING','Search the collection','Search names, places, short histories and record notes.')+`<form class="search-form" role="search"><input id="search-query" name="q" type="search" value="${esc(q)}" placeholder="Try Margaret, Tar River, or nursing" aria-label="Search the collection"><button type="submit">Search</button><button type="button" id="clear-search">Clear</button></form><div id="search-results">${searchResults(q)}</div>`;}
function searchResults(q){if(!q.trim())return '<p class="small">Enter a name or subject to begin.</p>';const terms=q.toLocaleLowerCase().trim().split(/\s+/),match=p=>terms.every(t=>JSON.stringify(p).toLocaleLowerCase().includes(t));const ps=D.people.filter(match),fs=D.features.filter(match),pl=D.places.filter(match),rs=Object.keys(records).filter(k=>match(records[k]));return `<p class="search-count" role="status">${ps.length+fs.length+pl.length+rs.length} results for “${esc(q)}”</p>${ps.length?'<h2>People</h2>'+personCards(ps):''}${fs.length?'<h2>Short histories</h2>'+featureCards(fs):''}${pl.length?'<h2>Places</h2>'+placeCards(pl):''}${rs.length?'<h2>Records</h2>'+recordList(rs):''}`;}
function notFound(){return heading('EXPLORE','This page is not in the collection')+'<a href="#people">Browse the family →</a>';}
function render(hash,restore=false){const route=(hash||'#people').slice(1),[kind,key]=route.split('/');if(kind==='record'){if(!records[key]){main.innerHTML=notFound();return;}if(!screen)render('#records');openRecord(key);return;}if(dialog.open)dialog.close();viewer.cancelGesture();document.body.classList.remove('dialog-open');tree=null;document.body.classList.toggle('tree-page',kind==='tree');document.body.classList.remove('tree-fullscreen');screen=hash||'#people';if(kind==='people'||kind==='')main.innerHTML=directory(key||'all');else if(kind==='person'&&people[key])main.innerHTML=profile(people[key]);else if(kind==='features')main.innerHTML=heading('FOLLOW A SUBJECT','Short histories','A closer look at the places, marriages, work and records behind the main story.')+featureCards(D.features);else if(kind==='feature'&&features[key])main.innerHTML=feature(features[key]);else if(kind==='places')main.innerHTML=heading('THE FAMILY’S GEOGRAPHY','Explore the places','The Bogue Chitto neighbourhood anchors four generations. Other places explain how the family reached it—and where Christine went next.')+landMap()+placeCards(D.places);else if(kind==='place'&&places[key])main.innerHTML=place(places[key]);else if(kind==='records'){if(restore&&history.state?.recordFilters)recordFilters={...history.state.recordFilters};main.innerHTML=recordBrowser();}else if(kind==='tree'){main.innerHTML=heading('FAMILY CONNECTIONS','The Alford family tree','Follow both sides of the family. Select a person for details, or open a branch to see earlier generations.')+'<div id="family-tree"></div>';tree=new AlfordTree($('family-tree'),D,key);if(restore&&history.state?.tree){tree.restore(history.state.tree);}}else if(kind==='chapter')main.innerHTML=chapter(key);else if(kind.startsWith('search'))main.innerHTML=search(new URLSearchParams(route.split('?')[1]||'').get('q')||'');else main.innerHTML=notFound();const section={person:'people',place:'places',feature:'features',chapter:'people'}[kind]||kind.split('?')[0];document.querySelectorAll('.explore-nav a').forEach(a=>a.toggleAttribute('aria-current',a.hash==='#'+section));document.title=(main.querySelector('h1')?.textContent||'Explore')+' · The Alford family';if(!restore){scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}else{scrollTo({top:history.state?.y||0,behavior:'instant'});if(history.state?.focus)document.getElementById(history.state.focus)?.focus({preventScroll:true});}}
function openRecord(key){const r=records[key];let keys=[...new Set([...main.querySelectorAll('a[href^="#record/"]')].map(a=>a.hash.split('/')[1]))];if(!keys.includes(key))keys=Object.keys(records);const at=keys.indexOf(key);$('source-sequence').innerHTML=[at>0?`<button data-adjacent-record="${keys[at-1]}">← ${esc(records[keys[at-1]].title)}</button>`:'<span></span>',at<keys.length-1?`<button data-adjacent-record="${keys[at+1]}">${esc(records[keys[at+1]].title)} →</button>`:''].join('');$('source-date').textContent=r.caption||'RECORD & SOURCES';$('source-title').textContent=r.title;$('source-note').innerHTML=r.html+(r.url?`<p><a href="${esc(r.url)}" target="_blank" rel="noopener">Collection record ↗</a></p>`:'');$('source-citation').textContent=r.citation+' · Archive: '+r.refs;dialog.classList.toggle('has-image',!!r.image);dialog.classList.toggle('has-transcript',!!r.transcript);$('record-workspace').hidden=!r.image;$('source-transcript').hidden=!r.transcript;$('source-transcript').innerHTML=r.transcript?`<h3 id="transcript-title">${esc(r.transcript.label)}</h3>${r.transcript.excerpts.map(e=>`${e.label?`<p class="excerpt-label">${esc(e.label)}</p>`:''}<blockquote>${esc(e.text)}</blockquote>`).join('')}${r.transcript.note?`<p class="transcription-note">${esc(r.transcript.note)}</p>`:''}${r.transcript.focus?'<button id="transcript-focus">Show these lines in the image ↗</button>':''}`:'';for(const id of ['record-tools','record-scroller','viewer-help','source-original'])$(id).hidden=!r.image;$('source-details').open=!r.image;$('back-preview').hidden=true;if(r.image)$('source-original').href=r.image;dialog.querySelector('.return-story').textContent='← Return to '+(main.querySelector('h1')?.textContent||'the explorer');document.body.classList.add('dialog-open');if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('source-transcript').scrollTop=0;if(r.image)viewer.open(r.image,r.title);}
function save(){const state={...(history.state||{}),screen,y:scrollY,focus:document.activeElement?.id||null,recordFilters:{...recordFilters},tree:tree?tree.snapshot():null};history.replaceState(state,'');return state;}
function navigate(hash){if(hash.startsWith('#record/')){modalOrigin=save();history.pushState({modal:true,base:modalOrigin},'',hash);openRecord(hash.split('/')[1]);}else{save();history.pushState({},'',hash);render(hash);}}
function closeRecord(){if(history.state?.modal)history.back();else{history.replaceState({},'',screen||'#records');render(screen||'#records');}}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();if(!a.id)a.id='explorer-focus-'+[...document.querySelectorAll('a')].indexOf(a);if(a.getAttribute('href')==='#explore-main'){main.focus();return;}navigate(a.getAttribute('href'));return;}const adjacent=e.target.closest('[data-adjacent-record]');if(adjacent){history.replaceState(history.state,'','#record/'+adjacent.dataset.adjacentRecord);openRecord(adjacent.dataset.adjacentRecord);return;}const source=e.target.closest('[data-record]');if(source){if(!source.id)source.id='exhibit-'+source.dataset.record;navigate('#record/'+source.dataset.record);return;}if(e.target.closest('.close-dialog,.return-story')){closeRecord();return;}if(e.target.closest('#transcript-focus')){const r=records[location.hash.split('/')[1]];if(r?.transcript?.focus){viewer.focusRegion(r.transcript.focus);$('record-scroller').focus();}return;}const group=e.target.closest('[data-group]');if(group){navigate('#people/'+group.dataset.group);return;}const filter=e.target.closest('[data-record-filter]');if(filter){recordFilters.type=filter.dataset.recordFilter;updateRecords();return;}if(e.target.closest('#reset-records')){recordFilters={person:'all',type:'all',order:'oldest'};$('record-person').value='all';$('record-order').value='oldest';updateRecords();return;}if(e.target.closest('#clear-search')){history.replaceState({},'','#search');$('search-query').value='';$('search-results').innerHTML=searchResults('');$('search-query').focus();}});
document.addEventListener('submit',e=>{if(e.target.matches('.search-form')){e.preventDefault();const q=$('search-query').value.trim();history.replaceState({},'','#search?q='+encodeURIComponent(q));$('search-results').innerHTML=searchResults(q);}});
document.addEventListener('change',e=>{if(e.target.id==='record-person'||e.target.id==='record-order'){recordFilters[e.target.id==='record-person'?'person':'order']=e.target.value;updateRecords();return;}if(e.target.matches('[data-land]')){const area=e.target.closest('.land-explorer');area.querySelectorAll(`[data-layer="${e.target.dataset.land}"]`).forEach(el=>el.style.opacity=e.target.checked?'1':'0');}});
dialog.addEventListener('cancel',e=>{e.preventDefault();closeRecord();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeRecord();}});
addEventListener('popstate',()=>{if(location.hash.startsWith('#record/')){if(!screen&&history.state?.base)render(history.state.base.screen,true);openRecord(location.hash.split('/')[1]);}else{const same=screen===location.hash;if(same){dialog.close();viewer.cancelGesture();document.body.classList.remove('dialog-open');scrollTo({top:history.state?.y||0,behavior:'instant'});document.getElementById(history.state?.focus)?.focus({preventScroll:true});}else render(location.hash,true);}});
addEventListener('resize',()=>{if(tree)tree.resize();});
render(location.hash||'#people');
})();
